### PR TITLE
Removing prebuild loader script from loader build.json

### PR DESCRIPTION
**Pull request by aversini**
This is a small change that Nathan approved. This should only be merged into develop once my branch icons is in.

### CODE REVIEW

**Comment by aversini** [comment]
@nathancomstock can you check this MR? I've removed the "prebuild" script from loader (and I also took the liberty to fix the document error when we build)

**Comment by nathancomstock** [comment]
@aversini , getting a build error - checking to see if its related..

**Comment by aversini** [comment]
Sorry @nathancomstock I forgot... this branch can only be built with my WF branch "icons"... I've updated wf2-package to take the change into account...

**Comment by nathancomstock** [comment]
@aversini , Looks good.

**Pull request merged**
